### ISSUE TITLE
Acrylic flickers when being maximized. 

### ISSUE THREAD

**Issue by FearGannicus** [Seo-Rii/electron-acrylic-window#14]
I'm not sure if this is something fixable, but if you maximize an appliciation using the acrylic feature, it flickers to transparent for a quick half-second and then back to the acrylic blur.

**Comment by Seo-Rii** [comment]
Unfortunately, it will be difficult to find a solution. This is because such problems occur at the API level. Open the setting app and proceed with the same task. It blinks exactly like this program. If I find out how to solve this problem, or if someone sends me a PR, I'll fix it, but otherwise it'll be hard to fix it. :(

**Comment by JT-Potato** [comment]
> Open the setting app and proceed with the same task. It blinks exactly like this program.
Settings no longer does this in Windows 11, and I don't think this happened with windows 10.
.-. but I also have no idea how to begin looking for the solution here either, so that's unfortunate
