### ISSUE TITLE
The window is black!

### ISSUE THREAD

**Issue by adel-sbeh** [Seo-Rii/electron-acrylic-window#32]
```
win = new BrowserWindow({
  [...]
  frame: false,
  show: false,
  [...]
  paintWhenInitiallyHidden: true,
  transparent: false,
  titleBarStyle: "customButtonsOnHover",
  vibrancy: (data.window.type == "acrylic") ? {
    theme: '#00000000',
    effect: 'acrylic',
    disableOnBlur: false
  } : false
});
```
<a href="https://ibb.co/sm1Zdsq"><img src="https://i.ibb.co/yfkrcgq/2020-10-19-11-30-08.png" alt="2020-10-19-11-30-08" border="0"></a>

**Comment by adel-sbeh** [comment]
Never mind, the developer tools were causing this issue. But there is another issue:
<a href="https://ibb.co/gy8RFyH"><img src="https://i.ibb.co/MnHC5nW/2020-10-19-11-34-17.png" alt="2020-10-19-11-34-17" border="0"></a>

**Comment by adel-sbeh** [comment]
Yeah, all transparent elements have a black background.

**Comment by adel-sbeh** [comment]
https://gofile.io/d/Frdy6K

**Comment by Seo-Rii** [comment]
This is an error caused by the browser's backdrop-filter not recognizing elements outside the window. I'm aware of this bug, but sadly, I don't have a proper way to solve it. Maybe we can't solve this problem until Windows provides a formal API. 
Perhaps simply putting a transparent element without using the backdrop-filter won't cause any problems.
+add
I've thought about how to solve this problem, and it's a way to capture the entire screen in real time, crop the video properly, and then blur it out and set it as a wallpaper. However, the method will be **very** slow and unstable. Let me know if there is a better way.

**Comment by tscpp** [comment]
Try removing [index.js#L64](https://github.com/Seo-Rii/electron-acrylic-window/blob/master/index.js#L64) and [index.js#L73](https://github.com/Seo-Rii/electron-acrylic-window/blob/master/index.js#L73).

**Comment by Seo-Rii** [comment]
@tscpp If you delete the transparency of the window, there is no blur effect.

**Comment by adel-sbeh** [comment]
Ok, I guess that there is no proper solution.

**Comment by adel-sbeh** [comment]
I think that you can now mark this issue as "*fixed*". This bug no longer occurs!
![2020-11-23-21-38-58](https://user-images.githubusercontent.com/72353925/100007186-5f4b0200-2dd4-11eb-83e0-f23d5de5e291.png)

**Comment by Schnei1811** [comment]
@0xENDER Just wondering what you did to fix the black background issue. I'm seeing it as well currently only on certain machines.

**Comment by 0xENDER** [comment]
It kinda just got fixed when electron got updated to the latest version at the time... (srry about the 1 year delay)
