### ISSUE TITLE
Changing blur amount

### ISSUE THREAD

**Issue by FearGannicus** [Seo-Rii/electron-acrylic-window#5]
Hey! Love the module, a lot of people have been looking for something that can do exactly what this module aims at for a long time. I just had one question, the blur is good, but it doesn't match with the other windows 10 programs.

Here's an example between the application I'm making and the settings window. 
![image](https://user-images.githubusercontent.com/43388217/88472222-8bb24880-cede-11ea-865f-1df531577710.png)

Is it possible to change the amount of blur so it matches? maybe this has already been implemented and I can't see how to do it? Otherwise maybe this is a good option to try and add?

**Comment by Seo-Rii** [comment]
After looking at this issue, I found that there is a way to express the Blur effect more closely from RS4 to the Blur effect of the UWP app. [Adding Acrylic Blur to your Windows 10 (Redstone 4) desktop apps](https://withinrafael.com/2018/02/02/adding-acrylic-blur-to-your-windows-10-apps-redstone-4-desktop-apps/)
Originally, the AccentState of the SetWindowCompositionAttribute API was designated as ACCENT_ENABLE_BLURBEHIND, but from RS4 it is said that there is an option that is closer to the UWP app called ACCENT_ENABLE_ACRYLICBLURBEHIND. I didn't notice because it's an not documented API.
I will reflect this amendment in the next update. Thank you.

**Comment by FearGannicus** [comment]
@Seo-Rii thanks for looking into it! Again, I appreciate this module so much! Looking forward to the update

**Comment by Seo-Rii** [comment]
Solved on https://github.com/Seo-Rii/electron-acrylic-window/commit/f1bdc9d1a7393a78d9b6b7acdda26ad975e5c06e.  
 Additionally, I added the option to choose the theme!   
I'll publish it into npm after solving bug https://github.com/Seo-Rii/electron-acrylic-window/issues/3.

**Comment by FearGannicus** [comment]
Thanks so much @Seo-Rii!

**Comment by Seo-Rii** [comment]
v0.3.0 now published. Now you can see the improvements!

**Comment by rendomnet** [comment]
@Seo-Rii Can I change blur amount of effect **blur** not **acrylic**? Acrylic is very slow.
