### ISSUE TITLE
lag 

### ISSUE THREAD

**Issue by ethugbaby** [Seo-Rii/electron-acrylic-window#6]
there is significant lag while moving the window when the vibrancy is enabled

**Comment by YuhangQ** [comment]
me too!

**Comment by Seo-Rii** [comment]
Please upgrade the module to v0.3.0. Version 0.3.0 changed option for processing acrylic effect, so it got faster. 
If you are still slow, please reopen the issue.

**Comment by xanderfrangos** [comment]
This is a known issue with using Acrylic with Electron:
https://github.com/EYHN/vscode-vibrancy/issues/5

It appears to be related to the mouse polling rate on the user's PC. I've tried to work around it with no success. If you have a dragable or resizable window, you'll run into lag.

**Comment by xanderfrangos** [comment]
One possible workaround would be to replace the move/resize functionality in Electron with one that only updates at the refresh rate of the display.

**Comment by ethugbaby** [comment]
@Seo-Rii this is the version im using ```"electron-acrylic-window": "^0.3.0"```, i had the old version in a different project and that didnt lag

**Comment by Seo-Rii** [comment]
@ethugbaby Could you tell me the Windows version? (Containing build number)

**Comment by Seo-Rii** [comment]
@xanderfrangos Yes, there was some lag on this module since using blur option as ACCENT_ENABLE_ACRYLIC, as same as [the module that you mentioned]( https://github.com/EYHN/vscode-vibrancy/blob/master/src/blur-cli/blur-cli/blur-cli.cpp#L115). But since v0.3.0, It changed method into [ACCENT_ENABLE_ACRYLICBLURBEHIND](https://github.com/Seo-Rii/electron-acrylic-window/commit/f1bdc9d1a7393a78d9b6b7acdda26ad975e5c06e#diff-ddaa7d6e643bc0d374add600b02445beR61), and in my case(Windows 10 20h1, build 19041), there isn't any lag. But I couldn't test it on other windows version like 19h1, which can act differently with my case.

**Comment by ethugbaby** [comment]
@Seo-Rii windows 10 v1903 (OS Build 18362.959)

**Comment by FearGannicus** [comment]
@Seo-Rii I appreciate you putting this update out to use the acrylic blur versus the blurbehind, however, I am also experiencing the same lag on version 20H2.

![image](https://user-images.githubusercontent.com/43388217/88740489-4faffb00-d10b-11ea-87a8-bae266d01afe.png)


It occurs when dragging the window around the screen, and also resizing the window. Please let me know if there's any more information i can provide you :)

**Comment by xanderfrangos** [comment]
@FearGannicus Do you mind trying this test app and letting me know if it lags when you move/resize it?
https://1drv.ms/u/s!AiWKFpjcSKRQhdMmVpFThY7oEW8MJQ?e=foxppB

Extract and run Blur Test.exe

**Comment by Seo-Rii** [comment]
@FearGannicus When I tested it again, there was a slight lag when I resized the window. However, this was not the case when moving the window.

**Comment by FearGannicus** [comment]
> @FearGannicus Do you mind trying this test app and letting me know if it lags when you move/resize it?
> https://1drv.ms/u/s!AiWKFpjcSKRQhdMmVpFThY7oEW8MJQ?e=foxppB
> 
> Extract and run Blur Test.exe

Feel free to link me the source code, I'm not trying to run any exe file that I don't know what it does haha. 



> @FearGannicus When I tested it again, there was a slight lag when I resized the window. However, this was not the case when moving the window.

Very odd, I haven't yet tested on my desktop. Currently on my laptop. Would providing more specs for you help? This is a pretty beefy laptop.

**Comment by xanderfrangos** [comment]
@FearGannicus Sure: https://github.com/xanderfrangos/electron-acrylic-window/tree/electron-builder-test
If you're concerned about the executable, just run `npm i` and `npm run test`. It's the same thing, just not in an Electron Builder package.

**Comment by FearGannicus** [comment]
> @FearGannicus Sure: https://github.com/xanderfrangos/electron-acrylic-window/tree/electron-builder-test
> If you're concerned about the executable, just run `npm i` and `npm run test`. It's the same thing, just not in an Electron Builder package.

Alright, it fixed the delayed lag i was expieriencing, however, now it looks a lot choppier, not as smooth as other applications. 
Just for a reference here's the specs of my laptop;

![image](https://user-images.githubusercontent.com/43388217/88745600-7b85ad80-d118-11ea-95ed-e786246e5ce2.png)

**Comment by xanderfrangos** [comment]
@FearGannicus Thanks for testing it out. That confirms that the mouse polling rate is the problem. I'm guessing your mouse or trackpad is polling at 500Hz or 1000Hz. The choppiness you're seeing is because the window is only moving at 60Hz. If in `index.js` you change `pollingRate` to 240 instead of 59.997, the window should move smoothly.

**Comment by FearGannicus** [comment]
> @FearGannicus Thanks for testing it out. That confirms that the mouse polling rate is the problem. I'm guessing your mouse or trackpad is polling at 500Hz or 1000Hz. The choppiness you're seeing is because the window is only moving at 60Hz. If in `index.js` you change `pollingRate` to 240 instead of 59.997, the window should move smoothly.

I will test that out now to confirm, but def looks like you are on the right track. Is there a way for us to detect the monitors refresh rate in node/electron?

**Comment by xanderfrangos** [comment]
Electron exposes everything but the refresh rate, unfortunately. I'm not aware of any public Node modules that can do what is needed either, but I'll see if my friend @djsweet would like to help. He has an unpublished Node module that can detect the refresh rate of each display.

**Comment by FearGannicus** [comment]
@xanderfrangos Hmm... it's a shame that sometimes we are so limited in what electron can offer us. Hopefully this becomes offered in the future.

I don't know about getting each monitor or a speific monitors refresh rate, but I just saw this node module: https://github.com/Richienb/refresh-rate 

Perhaps there's something we can see from there, that could help us.

**Comment by Seo-Rii** [comment]
I found another module to get frame rate. https://github.com/sebhildebrandt/systeminformation  
This is not to calculate the frame rate, but to get information from the system, so it seems to be more accurate.
You can test it by :
```si.graphics().then(data => console.log(data['displays'][0]['currentRefreshRate']))```
+There's been a lot of discussion while I was away! I may not be able to check my writing often because I have something outside of programming these days. I'm really sorry about this.

**Comment by FearGannicus** [comment]
@Seo-Rii no worries, I feel as though we can try our best to assist you with fixes, and testing.

**Comment by Seo-Rii** [comment]
Then I think the best way is to use the https://github.com/Richienb/refresh-rate module you just mentioned.

**Comment by Seo-Rii** [comment]
@FearGannicus I tested with https://github.com/Richienb/refresh-rate, but it does not works well. I'm using 144hz monitor, but it returns 60.

**Comment by FearGannicus** [comment]
> @FearGannicus I tested with https://github.com/Richienb/refresh-rate, but it does not works well. I'm using 144hz monitor, but it returns 60.

hmm... maybe the best way is to make a cpp module?

**Comment by Seo-Rii** [comment]
@FearGannicus So then, I'll make new module to get frame rate from monitor.

**Comment by djsweet** [comment]
@Seo-Rii @xanderfrangos pinged me about my unreleased refresh rate detection. I've cleaned it up and made it available as [`win32-displayconfig`](https://www.npmjs.com/package/win32-displayconfig). Unfortunately, integration isn't exactly trivial.

@FearGannicus I've been working on an integration attempt at https://github.com/djsweet/electron-acrylic-window/tree/handle-polling-rate-based-on-refresh-rate, running into tons of Electron bugs along the way. Maybe it'll be OK performance-wise for you.

**Comment by Seo-Rii** [comment]
Thank you @djsweat! In fact, I made a module that gets frame rate, but I couldn't use it because there were some problems in a few cases. And there was this amazing module.

**Comment by FearGannicus** [comment]
@djsweet - ran a test of your project here is what i found. 

Moving windows around; 
- When the test app opens up on my main monitor (240Hz), runs nicely (a little choppy still but i can tell its not 60fps)
- However, when I drag the test app over to a secondary or connected monitor at a different refresh rate (e.g. 60Hz) I find it's super choppy and looks like 30fps. 

Resizing windows;
- feels absolutely super delayed and laggy for me on both monitors

**Comment by djsweet** [comment]
@FearGannicus What commit did you test?

7e19b0e0691e60973042aa5c4461debd07b31870 clamps resizing to 60Hz regardless of the refresh rate. We simply weren't able to get it to perform well on 4K displays with Windows-level transparency effects on otherwise.

98e8436885782ba8ec4daa09d3b502a8fcb17cf9 resets timers before actually attempting to set movement bounds (like so many operations in the Windows API, it's a surprise blocking operation) so you get closer to the actual refresh rate vs the refresh rate, waiting for the function to return, and _then_ allowing movement to happen again.

**Comment by FearGannicus** [comment]
Oh shoot! Maybe I was running the wrong version @djsweet. 
I've just ran the branch `handle-polling-rate-based-on-refresh-rate` and things seem much smoother on both monitors!

**Comment by Seo-Rii** [comment]
In recently commit(a62ff26), I applied patch that sets mouse polling rate based on  frame rate of the monitor. This modification has been applied to v0.3.2.
Unfortunately, this upgrade did slightly reduce the lag, but it didn't completely eliminate it. I'm looking for another optimization method, but if you also have a good idea, let me know.

**Comment by xanderfrangos** [comment]
@Seo-Rii I believe the [`handle-polling-rate-based-on-refresh-rate` branch](https://github.com/djsweet/electron-acrylic-window/tree/handle-polling-rate-based-on-refresh-rate) has been fixed up and is ready to go. I worked with @djsweet quite a bit on it. He simply hasn't had a chance to open a PR.

**Comment by FearGannicus** [comment]
@Seo-Rii From the testing that I did, and as @xanderfrangos said, the [`handle-polling-rate-based-on-refresh-rate`](https://github.com/djsweet/electron-acrylic-window/tree/handle-polling-rate-based-on-refresh-rate) branch created by @djsweet seemed to do the trick.

**Comment by Seo-Rii** [comment]
In fact, the version I made works on the same principle. One problem is that it's not tested in a multi-window environment, and it's a little unstable. I believe @djsweat solved this problem. If you don't mind, can you tell me when you will send the PR? I'm about to port this module in typescript soon, because I want to keep all the issues in place before that.

**Comment by xanderfrangos** [comment]
@Seo-Rii I'll try to merge the branch @djsweet made with your latest code later today. His branch properly handles multi-monitor setups with different refresh rates and includes several smaller fixes (ex. Aero Snap, maximizing/unmaximizing, resizing), so it's important to get merged.

**Comment by xanderfrangos** [comment]
I should have a better fix tomorrow that doesn't have that issue. Then hopefully we can be done with this "lag" issue. 😅

**Comment by xanderfrangos** [comment]
@Seo-Rii Sorry for the delay! New fix is available [here](https://github.com/Seo-Rii/electron-acrylic-window/pull/21).

**Comment by Seo-Rii** [comment]
Perfect! This patch will be applied to v0.4.0. The long-standing problem has been solved. Thank you all!
